// 🏪 inventory-cell - Business Domain Cell
// Wave 3 - Generated by KIM (Chief System Builder)
// Created: Wed Feb 11 03:21:30 +07 2026

export { default } from './inventory.service';
export * from './inventory.types';
export * from './inventory.contract';
